apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-for-kubernetes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-for-k8s
  template:
    metadata:
      labels:
        app: python-for-k8s
    spec:
      containers:
      - name: python-for-k8s
        image: docker.io/boscokipkosgei/python_for_k8s:v1.0.0
        ports:
        - containerPort: 8000
